package model.game;

public enum EventType {
	START_TURN, DRAW_CARD, PLAY_CARD, DEAL_DAMAGE, TAKE_DAMAGE, CARD_DESTRUCTION, MOVE_TO_DISCARDPILE, EQUIP_ITEM, BUFF_CARD, DEBUFF_CARD, DRAIN, RALLY, SHACKLE;
}
