package model.game;

public enum EventType {
	IDLE, START_TURN, END_TURN, GAIN_MAX_MAGICKA, GAIN_CURRENT_MAGICKA, DRAW_CARD, PLAY_CARD, DEAL_DAMAGE, TAKE_DAMAGE, CARD_DESTRUCTION, MOVE_TO_DISCARDPILE,
	GAIN_HEALTH, EQUIP_ITEM, BUFF_CARD, DEBUFF_CARD, DRAIN, RALLY, SHACKLE;
}
