package model.card;

public enum CardMechanicType {
	ACTIVATE, BREAKTHROUGH, CHARGE, COPY, COVER, DRAIN, EQUIP, GUARD, HEAL, LASTGASP, LETHAL, MOVE, PILFER, PROPHECY,
	REGENERATE, SACRIFICE, SHACKLE, SILENCE, STEAL, SUMMON, TRANSFORM, UNSUMMON, WARD, WOUNDED;
	
	// BATTLE, BATTLE, BEASTFORM
	// BETRAY, EXALT, PLOT, RALLY
	// CHANGE, SLAY
	// ASSEMBLE, BANISH, TREASUREHUNT
	// DOUBLECARDS
}
